/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> } 
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('tools').del()
  await knex('tools').insert([  
    {
      tool_id: 2000000, 
      Tool_name: 'Velociraptor',
      BoxType: 'Velociraptor',
      headline: 'Velociraptor',
      isActive: true,
      logoAddress_1: "./Logos/Velociraptor.svg",
      logoAddress_2: "",
      iconAddress: './icons/General-icons-risx.svg',
      description_short: 'Endpoint visibility and rapid response platform',
      description_long: 'Velociraptor is an innovative endpoint security solution offering extensive visibility and rapid response capabilities. It revolutionizes incident detection and mitigation by providing real-time insights into endpoint activities across the network. With its advanced features, Velociraptor enables security teams to efficiently monitor and analyze endpoint behavior, detect threats, and respond promptly to security incidents. Its flexible and modular architecture allows for seamless integration with existing security infrastructure, enhancing overall security posture. By automating investigative processes and facilitating proactive threat hunting, Velociraptor empowers organizations to stay ahead of emerging threats and protect their assets effectively.',
      Status: 'blue',
      buttonTitle: 'Active',
      toolURL: '',
      ServicePackage: 'Standard',
      threshold_time:24,
      arguments:{},
      useResourceType:"",
      toolType:"module",
      LastRun:"2024-06-02 10:15:17"
     }, 
    {
    tool_id: 2001000, 
    Tool_name: 'Risx',
    BoxType: 'Tools_a',
    headline: 'AD Security Platform',
    isActive: true,
    ShowInUi: true,
    logoAddress_1: "./Logos/10Root.svg",
    logoAddress_2: "",
    iconAddress: './icons/General-icons-risx.svg',
    description_short: 'All-In-One Holistic AD security Platform',
    description_long: 'Risx is an All-In-One Holistic AD security Platform Risx consists of plug-ins based modules that can be easily customized or extended with new functionality. The Security posture analytics module is designed to discover, identify and prioritize cyber security threats on AD Service & the underline OS and Present them in a simple, intuitive way, in order to manage them intelligently.The KerbShield module designed to Detect & Prevent AD attacks in Real Time utilizing conditional access and contextual authorization',
    Status: 'blue',
    buttonTitle: 'Active',
    toolURL: 'http://risxserverdev.westeurope.cloudapp.azure.com:3001/login/',
    ServicePackage: 'Standard',
    threshold_time:24,
    arguments:{},
    useResourceType:"",
    toolType:"link",
    LastRun:"2024-06-02 10:15:17"
   }, 
    {
       tool_id: 2001001,
       Tool_name: 'ELK',
       BoxType: 'Tools_b',
       headline: 'Artifacts',
       isActive: true,
       ShowInUi: true,
       logoAddress_1: "./Logos/ELK.svg",
       logoAddress_2: "",
       iconAddress: './icons/General-icons-b.svg',
       description_short: 'Search and analyze all collected artifacts',
       description_long: 'Elasticsearch is used for storing, searching, and analyzing structured and unstructured data in near real-time. One of the key features of Elasticsearch is its scalability, which allows it to handle large datasets across multiple nodes in a cluster.',
       Status: 'blue',
       buttonTitle: 'View',
       toolURL: 'https://10root.com/',
       ServicePackage: 'Standard',
       threshold_time:24,
       arguments:{},
       useResourceType:"",
       toolType:"link",
       LastRun:"2024-06-02 10:15:17"
      }, 
         {
        tool_id: 2001002,
        Tool_name: 'TimeSketch',
        BoxType: 'Tools_a',
        headline: 'Timeline',
        ShowInUi: true,
        logoAddress_1: "./Logos/Timesketch.svg",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-e.svg',
        description_short: 'collaborative forensic timeline analysis',
        description_long: 'Timesketch is an open-source tool for collaborative forensic timeline analysis. Using sketches you and your collaborators can organize and work together.',
        Status: 'blue',
        buttonTitle: 'Timelines',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"2008",
        toolType:"module",
       LastRun:"2024-06-02 10:15:17"
       },
       {
        tool_id: 2001003,
        Tool_name: 'Open CTI',
        BoxType: 'Tools_b',
        headline: 'CTI DB & Dashboard',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/OPENCTI.png",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-a.svg',
        description_short: 'Cyber threat intelligence knowledge and observable',
        description_long: 'OpenCTI is an open source platform allowing organizations to manage their cyber threat intelligence knowledge and observable. It has been created in order to structure, store, organize and visualize technical and non-technical information about cyber threats.The structuration of the data is performed using a knowledge schema based on the STIX2 standards. It has been designed as a modern web application including a GraphQL API and an UX oriented frontend. Also, OpenCTI can be integrated with other tools and applications such as MISP, TheHive, MITRE ATT&CK, etc.',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"",
        toolType:"link",
        LastRun:"2024-06-02 10:15:17"
       },
       {
        tool_id: 2001004,
        Tool_name: '10Root Osint',
        BoxType: 'Tools_b',
        headline: 'Open Source Intelligence',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/10Root.svg",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-i.svg',
        description_short: 'Multi custom OSINT search engine',
        description_long: 'Open source intelligence (OSINT) is the collection and analysis of data gathered from open sources (covert sources and publicly available information; PAI) to produce actionable intelligence. OSINT is primarily used in national security, law enforcement, and business intelligence functions and is of value to analysts who use non-sensitive intelligence in answering classified, unclassified, or proprietary intelligence requirements across the previous intelligence disciplines.',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"2001,2002,2003,2004,2005,2006,2007",
        toolType:"link",
       LastRun:"2024-06-02 10:15:17"
       },
       {
        tool_id: 2001010,
        Tool_name: 'IRIS',
        BoxType: 'Tools_b',
        headline: 'DFIR-IRIS',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/Iris.png",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-h.svg',
        description_short: 'Incident Response Platform',
        description_long: 'IRIS is a collaborative platform for incident response analysts that helps to share investigations at a technical level. Its a web application that can be installed on a fixed-server or on a laptop for roaming investigations where internet might not be available.IRIS was born out of the struggle to share long and complex investigations among analysts..',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"",
        toolType:"link",
       LastRun:"2024-06-02 10:15:17"
       },






       {
        tool_id: 2001005,
        Tool_name: 'Nuclei',
        BoxType: 'Tools_a',
        headline: 'ASM',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/Nuclei.svg",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-h.svg',
        description_short: 'External Assets Vulnerability Scan',
        description_long: 'Worldwide digital change has accelerated the size, scope, and composition of an organizations attack surface. The size of an attack surface may fluctuate over time, adding and subtracting assets and digital systems (e.g. websites, hosts, cloud and mobile apps, etc.). Attack surface sizes can change rapidly as well. Digital assets eschew the physical requirements of traditional network devices, servers, data centers, and on-premise networks. This leads to attack surfaces changing rapidly, based on the organizations needs and the availability of digital services to accomplish it. Attack surface scope also varies from organization to organization. With the rise of digital supply chains, interdependencies, and globalization, an organizations attack surface has a broader scope of concern (viz. vectors for cyberattacks). Lastly, the composition of an organizations attack surface consists of small entities linked together in digital relationships and connections to the rest of the internet and organizational infrastructure, including the scope of third-parties, digital supply chain, and even adversary-threat infrastructure.',
        Status: 'blue',
        buttonTitle: 'Explore',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"2001,2002",
        toolType:"module",
        LastRun:"2024-06-02 10:15:17"
       },  {
        tool_id: 2001006,
        Tool_name: 'Strelka',
        BoxType: 'Tools_b',
        headline: 'Sandbox',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/STRELKA.png",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-d.svg',
        description_short: 'Examine files for malicious behavior',
        description_long: 'The isolation metaphor is taken from the idea of children who do not play well together, so each is given his or her own sandbox to play in alone. It is often used to execute untested or untrusted programs or code, possibly from unverified or untrusted third parties, suppliers, users or websites, without risking harm to the host machine or operating system.[1] A sandbox typically provides a tightly controlled set of resources for guest programs to run in, such as storage and memory scratch space. Network access, the ability to inspect the host system, or read from input devices are usually disallowed or heavily restricted.In the sense of providing a highly controlled environment, sandboxes may be seen as a specific example of virtualization. Sandboxing is frequently used to test unverified programs that may contain a virus or other malicious code without allowing the software to harm the host device.',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"",
        toolType:"link",
        LastRun:"2024-06-02 10:15:17"
       },{
        tool_id: 2001007,
        Tool_name: 'HashR',
        BoxType: 'Tools_b',
        headline: 'Private Hashes DB',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/HashR.png",
        logoAddress_2: "",
        iconAddress: '',
        description_short: 'Create custom hash sets from files',
        description_long: 'The HashR team is pleased to announce the first public release of HashR. HashR extracts files from a source and uploads hashes, metadata and the actual content of the files to a given data sink. By doing that it allows you to generate your own hash sets, which then you can use during Blue Team operations, by extracting and hashing the actual files from complex data sources like physical or cloud disk images. There are many hash set providers out there (e.g. NSRL), but shared hash sets have some limitations.',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"",
        toolType:"link",
       LastRun:"2024-06-02 10:15:17"
       },{
        tool_id: 2001008,
        Tool_name: 'Ail',
        BoxType: 'Tools_b',
        headline: 'Ail',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/ail.png",
        logoAddress_2: "",
        iconAddress: '',
        description_short: 'Hunt darknet for leaked information',
        description_long: 'AIL is a modular framework to analyse potential information leaks from unstructured data sources like pastes or social networks or unstructured data streams. The primary aim of the framework is to gather credentials, emails, credit-card numbers and so on in order to help security experts to detect leaks and then, react accordingly.The AIL training will show the various detection modules and how to use them as well as the web and tor crawler monitoring tool. Finally, the session will present how the framework can easily be extended to support new detection modules.',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: "https://10root.com/",
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"2001,2002,2003,2004,2005,2006,2007",
        toolType:"link",
        LastRun:"2024-06-02 10:15:17"
       },{
        tool_id: 2001009,
        Tool_name: 'Dehashed',
        BoxType: 'Tools_b',
        headline: 'Credential Leaks',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/dehashed.svg",
        logoAddress_2: "",
        iconAddress: '',
        description_short: 'Hunt for leak credential',
        description_long: 'DeHashed is a comprehensive cybersecurity service designed to enhance personal security online. It offers real-time monitoring of hacker activity to prevent account compromise by utilizing a vast cyber intelligence dataset, aiding in identity fraud investigations. DeHashed prides itself on affordability, stating that security should be accessible to everyone without significant expense. It maintains exclusive access to new and private datasets, setting it apart from other services. The platform is trusted by thousands of law enforcement agencies and Fortune 500 companies globally for investigations and protection needs. Additionally, DeHashed features powerful API integrations, enabling users to incorporate its dataset into their own applications efficiently. For more details, please visit their website at DeHashed.',
        Status: 'blue',
        buttonTitle: 'Explore',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Premium',
        threshold_time:24,
        arguments:{},
        useResourceType:"2001,2002,2003,2004,2006,2007",
        toolType:"link",
        LastRun:"2024-06-02 10:15:17"
       },
       {
        tool_id: 2001011,
        Tool_name: 'Shodan',
        BoxType: 'Tools_a',
        headline: 'Net Facing Search Engine',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/Shodan.png",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-b.svg',
        description_short: 'map and gather info about internet-connected devices and systems',
        description_long: 'Shodan is a powerful search engine designed to scan and index devices connected to the internet. Unlike traditional search engines, Shodan focuses on identifying and cataloging network-connected devices, including servers, routers, webcams, and IoT devices. It provides users with detailed information about these devices, such as their IP addresses, geographical locations, open ports, and services running on them. Shodan is widely used by cybersecurity professionals, researchers, and enthusiasts to discover vulnerabilities, assess network security posture, and monitor internet-connected devices worldwide. However, its capabilities also raise concerns about privacy and potential misuse by malicious actors for reconnaissance and cyber attacks..',
        Status: 'blue',
        buttonTitle: 'Explore',
        toolURL: 'https://10root.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"2001,2002",
        toolType:"module",
       LastRun:"2024-06-02 10:15:17"
       },   {
        tool_id: 2001012,
        Tool_name: 'MISP',
        BoxType: 'Tools_b',
        headline: 'Threat Intelligence & IOCs Platform',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/MISP.png",
        logoAddress_2: "",
        iconAddress:  "",
        description_short: 'MISP facilitates collaborative threat intelligence sharing, enabling effective detection and response to cyber threats.',
        description_long: 'The MISP (Malware Information Sharing Platform & Threat Sharing) project fosters collaborative threat intelligence sharing among cybersecurity professionals. Through its open-source platform, MISP enables organizations to share, store, and analyze threat data, enhancing their ability to detect and respond to cyber threats effectively.',
        Status: 'blue',
        buttonTitle: 'Active',
        toolURL: 'https://tenroot-misp.northeurope.cloudapp.azure.com/',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"",
        toolType:"link",
        LastRun:"2024-06-02 10:15:17"
       },
       {
        tool_id: 2001013,
        Tool_name: 'LeakCheck',
        BoxType: 'Tools_a',
        headline: 'Protect Digital Identity',
        isActive: true,
        ShowInUi: true,
        logoAddress_1: "./Logos/LEAKCHECK.png",
        logoAddress_2: "",
        iconAddress: './icons/General-icons-a.svg',
        description_short: 'Identify and manage exposed credentials.',
        description_long: 'LeakCheck.io is a comprehensive tool designed to help you safeguard your digital identity. By scanning for exposed credentials and sensitive information, it ensures that your personal and professional data remains secure. Our service provides real-time alerts for potential breaches, allowing you to take swift action against unauthorized access. With an easy-to-use interface and detailed reports, LeakCheck.io empowers you to manage your security posture effectively and minimize risks associated with data leaks. Protect your online presence and stay ahead of potential threats with our robust leak detection and management system.',
        Status: 'blue',
        buttonTitle: 'Explore',
        toolURL: 'https://leakcheck.io',
        ServicePackage: 'Standard',
        threshold_time:24,
        arguments:{},
        useResourceType:"2001,2002,2003,2004,2005,2006",
        toolType:"module",
        LastRun:"2024-06-02 10:15:17"
       }, 


  ]);
};
